### ISSUE TITLE
Bump version for POMDPPolicy support

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/TabularTDLearning.jl#19]
@MaximeBouton could you bump to 0.4.2 so the latest POMDPPolicy version inclusion is available?

Thank you :)

**Comment by rejuvyesh** [comment]
You mean bump version number and updating the registry?

**Comment by mossr** [comment]
Yes, that's what I meant

**Comment by rejuvyesh** [comment]
Hmm, did we forget registering this to the General registry?

**Comment by mossr** [comment]
Right? I could have sworn it was in General

**Comment by adinhobl** [comment]
I'm not sure if it's related to what ya'll are discussing but I tried the suggested 
```
Pkg.add("POMDPs")
import POMDPs
POMDPs.add("TabularTDLearning")
```
and that did not work. I also tried `]add TabularTDLearning`, but again, that didn't work. I eventually just added it through the github http link.

Thanks!

**Comment by MaximeBouton** [comment]
This package has not been registered yet #20

**Comment by mossr** [comment]
@adinhobl in the meantime you could do either of the following:
```julia
using Pkg
pkg"add https://github.com/JuliaPOMDP/TabularTDLearning.jl"
```
or
```julia
using Pkg
pkg"registry add https://github.com/JuliaPOMDP/Registry"
Pkg.add("TabularTDLearning")
```

**Comment by MaximeBouton** [comment]
Now the package is registered: https://github.com/JuliaRegistries/General/pull/25402#event-4052621666 
This should work:
```julia
import Pkg
Pkg.add("TabularTDLearning") 
```
