### ISSUE TITLE
Register in General

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/TabularTDLearning.jl#20]
Is there any reason why this isn't registered in the General Registry yet? @MaximeBouton do you remember? It doesn't depend on RLInterface

**Comment by MaximeBouton** [comment]
No particular reason I think we could register it!

**Comment by MaximeBouton** [comment]
https://github.com/JuliaPOMDP/TabularTDLearning.jl/commit/f23321e8429bf028392dcbc9c20678711b98d907#commitcomment-44596171

**Comment by zsunberg** [comment]
Awesome! Thanks!

**Comment by MaximeBouton** [comment]
should be good now: https://github.com/JuliaRegistries/General/pull/25402#event-4052621666
